#!/bin/sh
# setup.sh - install / uninstall / check / test the mux package into a prefix.
# The SINGLE entry point a consumer uses (a person, or a provisioning layer):
# mux owns its own layout, so nothing outside needs to know where bin, libexec,
# share, and man live. The runtime command stays `mux` (bin/mux); this only
# wires it in and audits it.
#
#   ./setup.sh install     link core bin + libexec + share + man (NO indicator)
#   ./setup.sh uninstall   remove those links
#   ./setup.sh check       audit install + deps; [OK]/[FAIL] markers; drift rc
#   ./setup.sh test        run the in-repo test suite (test/run)
#   ./setup.sh version     the packaged version
#   ./setup.sh all         install + the optional tray indicator
#   ./setup.sh indicator [VERB]  drive the optional indicator sub-package (a
#                          passthrough to indicator/setup.sh; VERB defaults to
#                          install). Kept OUT of `install`: it is Python + a
#                          daemon, unlike core mux (shell, no deps but tmux).
#
# POSIX sh, non-privileged. PREFIX (default ~/.local) and the XDG_* vars
# override the destinations, so a test drives it against a scratch dir. The
# <pkg> namespace lives in the INSTALL prefix (~/.local/libexec/mux), applied
# here; the source tree carries none (libexec/, share/), as a package should.
set -eu

PKG=mux
_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

PREFIX=${PREFIX:-$HOME/.local}
_bin=${XDG_BIN_HOME:-$PREFIX/bin}
_shr=${XDG_DATA_HOME:-$PREFIX/share}
_man=$_shr/man
# THE PAYLOAD: one tree holding mux as shipped, per the fleet's
# install-placement rule (ruled 2026-10-01). bin/, libexec/, share/ and man/
# live INSIDE it as siblings, because `bin/mux` resolves $0 and reads the
# other two relative to it; that invariant is what makes a checkout, a
# Homebrew keg and a relocated install all work, and it is why the nested
# `<payload>/share` stays. The wart is cosmetic; the invariant is not.
_pay=$_shr/$PKG
# THE RETIRED ROOT, kept as a name so install, uninstall and check all remove
# or report the same thing rather than each spelling it.
_oldlib=$PREFIX/libexec/$PKG
RC=0

# marker contract: plain [OK]/[FAIL]/[WARN] a host styles; coloured at a tty,
# plain when piped or under NO_COLOR.
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  _G=$(printf '\033[1;32m'); _R=$(printf '\033[1;31m')
  _Y=$(printf '\033[1;33m'); _O=$(printf '\033[0m')
else _G=; _R=; _Y=; _O=; fi
ok()   { printf '  %s[OK]%s   %s\n' "$_G" "$_O" "$1"; }
bad()  { printf '  %s[FAIL]%s %s\n' "$_R" "$_O" "$1"; RC=1; }
warn() { printf '  %s[WARN]%s %s\n' "$_Y" "$_O" "$1"; }

_ln()  { mkdir -p "$(dirname "$2")"; ln -sfn "$1" "$2"; }
_rmln() { [ "$(readlink "$2" 2>/dev/null)" = "$1" ] && rm -f "$2" || :; }

_man_pages() { for _m in "$_root"/man/man*/*.[0-9]; do
  [ -e "$_m" ] && printf '%s\n' "$_m"; done; }

# --- a README in the CONFIG ROOT, naming every location -------------------
# WHY A FILE AND NOT A SYMLINK. The obvious convenience is a `logs ->
# ...state/mux` link inside the config dir, and it is wrong HERE even though
# inkscape keeps a log in its own config dir: $MUX_DIR is designed to be
# SHARED between machines (everything machine-local lives in the cache and
# state dirs, which is why sharing this one is the documented remedy for two
# boxes disagreeing). A link to machine-local state inside it either carries a
# session set and a log into a dotfiles repo, or DANGLES on the other box.
#
# SO THE ANSWER IS DOCUMENTATION, which a symlink cannot be: a README can SAY
# which roots are shared and which are per-machine, and a link cannot.
#
# IT NAMES THE DERIVATION, not only the resolved path, because a snapshot of
# an absolute path is advice that outlives its contract the first time a root
# moves. The variable and its default are the durable half; the resolved value
# is labelled as "here".
#
# IT NEVER CLOBBERS A FILE A HUMAN TOUCHED. Written when absent, refreshed
# only when it still carries the marker line mux wrote, and otherwise left
# exactly alone with a word said. Same care `mux setup claude` takes with
# somebody else's config, for the same reason: the failure that matters is not
# "the README is stale", it is "mux ate something I wrote".
_README_MARK='# Generated by mux setup.sh. Edits are kept: see the note below.'
_config_readme() {
  _cr_dir=${MUX_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/mux}
  _cr_f=$_cr_dir/README
  if [ -e "$_cr_f" ] \
     && ! grep -qxF -- "$_README_MARK" "$_cr_f" 2>/dev/null; then
    echo "$PKG: left your own $_cr_f alone"
    return 0
  fi
  mkdir -p "$_cr_dir" 2>/dev/null || {
    echo "$PKG: could not write $_cr_f"; return 0; }
  cat >"$_cr_f" <<EOF || { echo "$PKG: could not write $_cr_f"; return 0; }
$_README_MARK

WHERE MUX KEEPS THINGS
======================

This directory is YOURS. mux reads it first and falls back to what it ships,
so a file here overrides the shipped one of the same name, and anything you
add is additive. An upgrade never touches it.

It is also meant to be SHAREABLE between machines: everything machine-local
lives under the state and cache roots below, so copying or symlinking this one
directory to another box is supported and is how two machines come to agree.

  THIS DIRECTORY        \$MUX_DIR
                        default \$XDG_CONFIG_HOME/mux, else ~/.config/mux
                        here: $_cr_dir
                        yours, shared between machines, upgrade-safe

  shipped defaults      \$MUX_SHARE
                        the installed payload's share/ directory
                        here: $_shr/$PKG
                        REPLACED ON UPGRADE: do not edit, override here instead

  durable state         \$MUX_STATE
                        default \$XDG_STATE_HOME/mux, else ~/.local/state/mux
                        the log, the session set, the indicator's colour slots
                        machine-local, survives a reboot, NOT shareable
                        the log's exact path: mux log --path

  rebuildable cache     \$MUX_CACHE
                        default \$XDG_CACHE_HOME/mux, else ~/.cache/mux
                        palette stamps and the discovery map
                        machine-local, safe to delete, mux rebuilds it

  per-boot runtime      \$XDG_RUNTIME_DIR
                        per-pane agent state, gone at reboot by design

  a send policy         /etc/mux/send-policy
                        root-owned, CONSULTED and never created by mux.
                        Absent means no grants, which is the closed default.

WHAT GOES IN HERE
=================

  config                one directive per line; only what OVERRIDES a default
  partitions/           one <name>.partition per partition
  layouts/              saved layouts (mux save writes here)
  profiles, profiles.d/ per-project settings
  hosts                 per-host colours, if you pin any
  envhooks.d/           your environment validators (see below)
  latch/                your own transport hooks, overriding the shipped ones

THE SHIPPED DEFAULTS ARE NOT MISSING
====================================

mux ships four environment validators and several latch hooks. They are NOT
copied here, because this directory is yours and an upgrade must be able to
replace a default without touching your files. They live in the payload:

  $_pay/share/envhooks.d/
  $_pay/share/latch/

To override one, put a file of the same name in envhooks.d/ or latch/ here;
to add one, use a name mux does not ship. Run \`mux check\` to see what mux
actually resolved.

A NOTE ON EDITS
===============

mux refreshes this file on install only while the first line above is intact.
Delete that line and this file becomes yours: mux will leave it alone and say
so, and you will stop getting updates to it.
EOF
  echo "$PKG: wrote $_cr_f (what each root holds, and which are shareable)"
}

# _payload_stage: build the new payload beside the live one and swap it in.
#
# IT COPIES, AND THAT IS THE POINT OF THE WHOLE CHANGE. Until now every root
# was a SYMLINK into the source clone, so an installed mux died the moment
# that clone moved: measured, with the source removed the entry point answers
# `No such file or directory` and nothing can diagnose it, because mux is the
# thing that is gone. A copy is self-contained, which is what Homebrew and
# the indicator's venv already were, so all three install paths now agree.
#
# STAGED AND SWAPPED, never emptied in place, because a live tmux calls
# `mux <verb>` on every status tick: removing the payload first would make
# every binding and the status bar fail for the length of a copy. Two renames
# is as close to atomic as a directory gets, which is the same reasoning that
# made the undo-pane record a rename rather than a create-then-fill.
_payload_stage() {
  _ps_new=$_pay.new
  _ps_old=$_pay.old
  # Expanded and CHECKED before anything is removed, per the standing rm
  # rule: this package's own harness once deleted this repository because an
  # empty value reached `rm -rf` at trap fire time.
  case $_pay in
  /*/*) ;;
  *) bad "refusing to stage a payload at '$_pay'"; return 1 ;;
  esac
  rm -rf -- "$_ps_new" "$_ps_old"
  mkdir -p "$_ps_new" || { bad "could not create $_ps_new"; return 1; }
  for _d in bin libexec share man; do
    [ -d "$_root/$_d" ] || continue
    cp -R "$_root/$_d" "$_ps_new/" || { bad "could not copy $_d"; return 1; }
  done
  [ -f "$_ps_new/bin/$PKG" ] || { bad "staged payload has no bin/$PKG"; \
    rm -rf -- "$_ps_new"; return 1; }
  # THE TWO FRAGMENT ALIASES, and they are a COEXISTENCE WINDOW rather than
  # tidiness. The tmux fragments are the only payload files a user names in
  # their OWN config, and that line moved with the layout:
  #
  #   was  source-file ~/.local/share/mux/mux.tmux
  #   now  source-file ~/.local/share/mux/share/mux.tmux
  #
  # Every tmux.conf on every box carries the old spelling, and without an
  # alias the first install after this change leaves mux installed and INERT
  # (no bar, no strip, no bindings) with nothing on screen saying why: the
  # exact state `mux check`'s whole contract exists to prevent, caused by
  # mux. The fleet rule makes the same point generally, that a change with no
  # coexistence window is a self-inflicted red tree.
  #
  # RELATIVE, so the alias survives the payload being moved or copied, and a
  # data-file alias rather than a second command: nothing resolves a PATH
  # through it, so this is not the two-copies-on-PATH hazard in disguise.
  for _f in mux.tmux mux-opinions.tmux; do
    [ -f "$_ps_new/share/$_f" ] && ln -sfn "share/$_f" "$_ps_new/$_f"
  done
  if [ -e "$_pay" ] || [ -L "$_pay" ]; then
    mv -- "$_pay" "$_ps_old" || { bad "could not move the old payload"; \
      return 1; }
  fi
  mv -- "$_ps_new" "$_pay" || { bad "could not swap in the new payload"
    [ -e "$_ps_old" ] && mv -- "$_ps_old" "$_pay"
    return 1; }
  rm -rf -- "$_ps_old"
}

# _retire_old_layout: a LAYOUT switch removes the layout it replaces, which
# the placement rule requires for the same reason a mode switch does: a
# surviving `~/.local/libexec/mux` is the two-copies hazard in another dress,
# and nothing audited for it before.
_retire_old_layout() {
  [ -e "$_oldlib" ] || [ -L "$_oldlib" ] || return 0
  case $_oldlib in
  /*/libexec/?*) ;;
  *) warn "not retiring '$_oldlib': unexpected shape"; return 0 ;;
  esac
  rm -rf -- "$_oldlib"
  rmdir "$PREFIX/libexec" 2>/dev/null || :
  echo "$PKG: retired the old layout at $_oldlib"
}

do_install() {
  mkdir -p "$_bin" "$_shr"
  _payload_stage || return 1
  _ln "$_pay/bin/$PKG" "$_bin/$PKG"
  _man_pages | while IFS= read -r _m; do
    _mr=${_m#"$_root"/}
    _ln "$_pay/$_mr" "$_man/$(basename "$(dirname "$_m")")/$(basename "$_m")"
  done
  _retire_old_layout
  echo "$PKG: installed to $_pay (+ bin and man links in $PREFIX)"
  _reload_live
  _tmux_conf_notice
  _config_readme
  _scan_root_step
  _indicator_notice
}

# The conventional tmux.conf locations, one per line. Factored because two
# callers below ask DIFFERENT questions of the same list, and the list itself is
# the part that would drift.
_tmux_confs() {
  for _c in "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
      "$HOME/.tmux.conf"; do
    [ -r "$_c" ] && printf '%s\n' "$_c"; done
}
# A HERE-DOC, NOT A PIPELINE, and the first version got this wrong in the
# direction that suppresses a warning: a `while` loop fed by a pipe runs in a
# SUBSHELL, so a `return` inside it cannot answer for this function, and a
# loop that runs ZERO times (no tmux.conf at all, which is every fresh box)
# exits 0, i.e. "found". The notice then never fired for the one user who needs
# it. Caught by test/setup.t on the first run.
_conf_mentions() {   # PATTERN -> 0 if any tmux.conf contains it
  while IFS= read -r _c; do
    [ -n "$_c" ] || continue
    grep -q -- "$1" "$_c" 2>/dev/null && return 0
  done <<EOF
$(_tmux_confs)
EOF
  return 1
}

# INSTALLING A FILE DOES NOT RELOAD A RUNNING SERVER, which is this package's
# most expensive recurring bug rather than a detail. A live tmux keeps the
# bindings, hooks and status format it read at START, so every new binding is
# inert on the machine that just received it: `mux undo-pane` was unreachable on
# both boxes for two releases that way, and `prefix ?` repeated it in 0.77. The
# only thing that fixes it is `mux reload`, so the install does it rather than
# leaving a correct install that behaves like a broken one.
#
# IT ALSO CLOSES A PROVISIONER'S LOOP. A provisioner runs `apply` only when
# `check` FAILS, and mux's check now correctly FAILS on a stale server, so
# without this the drift is reported forever by a pin whose install already
# ran ("APPLY DID NOT FIX", observed 2026-09-29). Prevention belongs here,
# in the step that made the file new.
#
# NOT THE SAME CALL AS THE TWO NOTICES BELOW, and the line between them is
# ownership rather than caution. A tmux.conf is the user's own FILE and an
# installer must not write it; the indicator is a separate PACKAGE whose stale
# code a restart could not fix anyway. A reload is neither: it is idempotent, it
# is the verb mux ships for exactly this, and the state it refreshes is mux's
# own.
#
# GUARDED ON THE LIVE CONFIG NAMING THIS INSTALL, which is what keeps it honest:
# if nothing sources THIS prefix's fragment then these servers are not running
# this install and reloading them would push an unrelated config, and in a
# test sandbox it would reach the developer's real server. `mux reload` itself
# never STARTS a server and says so when there was nothing up.
# A TILDE IS THE FORM PEOPLE ACTUALLY WRITE, and checking only the expanded
# path made this whole function inert on the one box it was written for: the
# real config says `source-file ~/.local/share/mux/mux.tmux`, tmux expands the
# `~` itself, and a textual guard looking for `/home/<user>/...` never matched.
# Correct-looking, silent, and wrong: the same shape as the bug above it.
_reload_live() {
  command -v tmux >/dev/null 2>&1 || return 0
  # Each form on its own LINE, so the corpus can mutate either: an anchor that
  # ends in a continuation backslash is failure mode two in the corpus's own
  # header and never matches.
  # FOUR SPELLINGS, because two things vary independently and both are real.
  # The TILDE is the form people actually write, and tmux expands it itself,
  # so a guard checking only the expanded path matched nothing and the whole
  # reload was inert on the box it was written for (found by reading the real
  # config, which is why that case exists in the test).
  #
  # And the PATH MOVED with the layout: `<pkg>/mux.tmux` became
  # `<pkg>/share/mux.tmux`, with an alias at the old spelling so every
  # existing tmux.conf keeps working. A guard that accepted only the new one
  # would stop reloading exactly the servers that are mid-migration, which is
  # the population this is for.
  #
  # Each form on its own LINE, so the corpus can mutate either: an anchor that
  # ends in a continuation backslash is failure mode two in the corpus's own
  # header and never matches.
  _rf=$_pay/share/mux.tmux
  _rt="~${_shr#"$HOME"}/$PKG/share/mux.tmux"
  _rfo=$_pay/mux.tmux
  _rto="~${_shr#"$HOME"}/$PKG/mux.tmux"
  _conf_mentions "$_rf" || _conf_mentions "$_rt" \
    || _conf_mentions "$_rfo" || _conf_mentions "$_rto" || return 0
  _out=$("$_bin/$PKG" reload 2>&1) || {
    echo "$PKG: NOTE could not reload live tmux servers: $_out" >&2
    echo "$PKG:      a running server keeps the bindings and hooks it read" >&2
    echo "$PKG:      at start, so run \`mux reload\` once that is fixed." >&2
    return 0; }
  case $_out in
  *'no running servers'*) return 0 ;;
  *) echo "$PKG: ${_out#mux: }" ;;
  esac
}

# THE SECOND STEP EVERY NEW USER HAS TO BE TOLD ABOUT. Linking mux into PATH
# does nothing visible: the status bar, the bindings and the strip all come from
# `source-file .../mux.tmux` in the user's own tmux.conf, and until that line
# exists mux looks installed and inert. That is the same "fully installed and
# fully broken" state `mux check` exists to catch, met one step earlier.
#
# IT SAYS RATHER THAN EDITS, deliberately, and this is the line where the
# install-placement rule bites: a tmux.conf is the user's own file, not a
# package input. mux writes `mux setup claude` into an agent's config because
# that verb's whole PURPOSE is that step and it asks first; an installer editing
# your tmux.conf as a side effect of `install` is a different thing, and the one
# irreversible mistake available here.
#
# SILENT WHEN THE LINE IS ALREADY THERE, so a re-install is quiet and this
# cannot become noise people learn to skip. The check is textual and looks in
# both conventional locations plus $XDG_CONFIG_HOME.
_tmux_conf_notice() {
  _frag=$_pay/share/mux.tmux
  # ANY mux fragment, not this prefix's: a user who installed elsewhere has
  # already done this step, and nagging them would be wrong. The reload above
  # asks the narrower question on purpose.
  # MATCHES BOTH SPELLINGS ON PURPOSE: `mux/mux.tmux` is the tail of the old
  # path AND of the new `mux/share/mux.tmux`... it is not, so both are asked
  # for explicitly. Tightening this to one spelling makes the notice fire on
  # every box still carrying the old line, which the alias keeps working.
  _conf_mentions "$PKG/share/mux.tmux" && return 0
  _conf_mentions "$PKG/mux.tmux" && return 0
  echo "$PKG: NOTE nothing sources mux's tmux fragment yet, so the status" >&2
  echo "$PKG:      bar, the agent strip and the key bindings will not" >&2
  echo "$PKG:      appear. Add this to your tmux.conf and reload tmux:" >&2
  echo "$PKG:" >&2
  echo "$PKG:        source-file $_frag" >&2
  echo "$PKG:        source-file $_shr/$PKG/mux-opinions.tmux   # optional" >&2
  echo "$PKG:" >&2
  echo "$PKG:      Then: mux setup claude   (wires your agent's hooks)" >&2
}

# THE ONE QUESTION A FIRST INSTALL CANNOT ANSWER FOR YOU: where your projects
# live. `mux go <name>` finds a project through the discovery map, and the map
# has no roots until somebody names one.
#
# mux USED TO SHIP `scan ~/src 3` AND FAIL WITHOUT IT, which is the defect this
# step replaces: a location nobody chose, and then `[FAIL] scan root missing` on
# every machine that keeps work somewhere else, which is most machines. A
# default is fine. A default nobody confirmed is not.
#
# IT ASKS ONLY WITH A TERMINAL, and the reason is the same one that keeps the
# tmux.conf notice from editing your config: a provisioner runs this installer
# on every sweep, so a prompt here would hang it and a silent write would give
# one machine a root the human never named. Without a tty it SAYS, exactly as
# the notice above does.
#
# AND IT IS mux's OWN CONFIG, which is what makes writing it legitimate at all.
# $MUX_DIR is where `mux save`, `mux new` and `mux theme` already write; a
# tmux.conf is the user's file and gets a notice instead. Same rule, opposite
# answer, because the OWNER differs.
_scan_root_step() {
  # Nothing to do when discovery is already configured, which keeps a
  # re-install silent: `mux scan --init` is idempotent and says so itself, so
  # this only has to decide whether to ASK.
  "$_bin/$PKG" scan --roots >/dev/null 2>&1 && return 0
  # THE DECISION BELONGS TO `scan --init`, NOT HERE, which is a correction.
  # This used to test for a terminal itself and merely PRINT A NOTE without
  # one, and that note is why discovery silently went off across a provisioned
  # fleet: the provisioner has no terminal, so on every sweep it printed a
  # line nobody was there to read and did nothing. A migration that cannot run
  # on the only install path there is, is not a migration.
  #
  # `scan --init` now distinguishes the two cases properly ($HOME is invented,
  # an existing ~/src is observed), so the installer can just call it and let
  # it decide. Keeping a second copy of that judgement here is how the two
  # would drift.
  #
  # `|| true` because discovery is OPTIONAL: a box with no obvious project
  # directory still gets a working mux, and `scan --init` has already said
  # what to type. An install must not fail over a convenience.
  "$_bin/$PKG" scan --init || true
}

# AN INSTALLED INDICATOR IS A SECOND PACKAGE THAT TALKS TO THIS ONE, and core
# does not install, restart or own it. It is still worth SAYING when it has
# fallen out of step, because the coupling is a CONTRACT (`mux agent status`,
# JSON) and a skew there fails silently: a daemon built against an older
# contract keeps polling and simply publishes fewer items, which reads as "that
# partition is gone" rather than as a version problem.
#
# A NOTICE AND NOT A RESTART, deliberately. Restarting would not help: what is
# stale is the daemon's OWN code, not anything it caches from core, since it
# re-execs `mux` on every poll. And not an install either: that is a pip
# operation wanting a network, and keeping core free of that is the whole reason
# the indicator is a separate package.
#
# CONTENT, NOT VERSION: it asks the indicator's own check, which compares the
# package to what is installed and what is RUNNING. Never fatal, and silent
# when no indicator is installed: an optional sub-package must not make the
# core install noisy for everyone who does not use it.
_indicator_notice() {
  [ -e "$_bin/mux-indicator" ] || return 0
  sh "$_root/indicator/setup.sh" check >/dev/null 2>&1 && return 0
  echo "$PKG: NOTE the installed tray indicator differs from this package" >&2
  echo "$PKG:      (or its daemon is running older code). It polls a mux" >&2
  echo "$PKG:      contract, so leaving it behind loses items silently." >&2
  echo "$PKG:      Refresh it with: ./setup.sh indicator" >&2
}

do_uninstall() {
  # Noted BEFORE the payload goes, since the evidence is inside it.
  _had_venv=
  [ -d "$_pay/venv" ] && _had_venv=1
  _rmln "$_pay/bin/$PKG" "$_bin/$PKG"
  # The OLD link target too, so uninstalling a pre-migration install works.
  _rmln "$_root/bin/$PKG" "$_bin/$PKG"
  _man_pages | while IFS= read -r _m; do
    _mt=$_man/$(basename "$(dirname "$_m")")/$(basename "$_m")
    _rmln "$_pay/${_m#"$_root"/}" "$_mt"
    _rmln "$_m" "$_mt"
  done
  _rmln "$_root/share" "$_shr/$PKG"     # a pre-migration share link
  _retire_old_layout
  if [ -d "$_pay" ] && [ ! -L "$_pay" ]; then
    case $_pay in
    /*/*) rm -rf -- "$_pay" ;;
    *) bad "refusing to remove a payload at '$_pay'" ;;
    esac
  fi
  echo "$PKG: removed $_pay and its links from $PREFIX"
  # THE INDICATOR'S VENV LIVES INSIDE THE PAYLOAD NOW, so removing the
  # payload took it too. Said rather than left to be discovered: its bin
  # link and its systemd unit are still there and now point at nothing, and
  # a dangling unit that fails at every login is worse than one that is gone.
  [ -z "$_had_venv" ] || {
    echo "$PKG: that INCLUDED the indicator's venv, so its unit and"
    echo "$PKG:   $_bin/$PKG-indicator now dangle. Clean them up with:"
    echo "$PKG:   sh indicator/setup.sh uninstall"; }
  # AND IT SAYS WHAT IT KEPT. Keeping these is right, because a session set
  # and a log are not the package's to delete; saying nothing about them is
  # not, because "uninstalled" then reads as "gone" while they sit on disk.
  echo "$PKG: KEPT your own files, delete them by hand if you mean to:"
  do_paths | while IFS="$(printf '\t')" read -r _k _v; do
    case $_k in
    config|state|cache) [ -e "$_v" ] && echo "$PKG:   $_k  $_v" ;;
    esac
  done
}

do_check() {
  echo "== $PKG (package install) =="
  [ "$(readlink "$_bin/$PKG" 2>/dev/null)" = "$_pay/bin/$PKG" ] \
    && ok "bin/$PKG links into the payload" \
    || bad "bin/$PKG does not link to $_pay/bin/$PKG"
  # THE PAYLOAD IS A TREE, NOT A LINK, which is the whole migration: a
  # symlink here means the install still depends on a source checkout and
  # dies when it moves.
  if [ -L "$_pay" ]; then
    bad "$_pay is a SYMLINK: this install still depends on a source tree"
  elif [ -d "$_pay" ] && [ -f "$_pay/bin/$PKG" ] \
      && [ -d "$_pay/libexec" ] && [ -d "$_pay/share" ]; then
    ok "payload is a self-contained tree ($_pay)"
  else
    bad "no payload tree at $_pay: reinstall mux"
  fi
  # A RETIRED LAYOUT PATH THAT SURVIVED. A WARN rather than a FAIL: nothing
  # resolves through it (libexec was never on PATH and bin/mux self-locates),
  # so it is stale rather than broken, and the fleet is mid-transition.
  if [ -e "$_oldlib" ] || [ -L "$_oldlib" ]; then
    warn "retired layout path survives: $_oldlib (reinstall removes it)"
  else
    ok "no retired layout path"
  fi
  "$_root/bin/mux" check || RC=1      # deps + package data (its own markers)
}

# --- paths: the ONE declaration of every root this package owns -----------
# PART OF THE PACKAGE CONTRACT (the fleet's install-placement rule, ruled
# 2026-10-01): one declaration feeds the four things that each otherwise
# guess, which is the whole argument for it being a verb rather than prose:
# the install audit, the stale-path sweep, uninstall saying what it kept, and
# discoverability.
#
# `KIND PATH` PER LINE, two fields, because a consumer wants to act per KIND
# (remove a payload, never a config) and parsing prose is how an integrator
# ends up with its own copy of the list. Tab-separated for the reason every
# other record in this package is: a path may contain a space.
#
# EVERY VALUE IS DERIVED, never restated: these are the same expressions the
# installer and mux itself resolve, so a root cannot be renamed in one place
# and still reported from here. That is the failure the verb exists to make
# impossible, and a hand-written list would reintroduce it.
#
# RUNTIME IS REPORTED AS THE DIRECTORY MUX OWNS, not the XDG root: naming the
# whole runtime dir would invite a sweep to delete another tool's socket. It
# is `<runtime>/mux` now rather than `<runtime>/agent-state`, which is the
# namespacing the same ruling asked for: agent state used to sit under a
# generic name beside at-spi, bus, dbus-1 and gcr.
do_paths() {
  printf 'bin\t%s\n'     "$_bin/$PKG"
  printf 'payload\t%s\n' "$_shr/$PKG"
  printf 'man\t%s\n'     "$_man/man1/$PKG.1"
  printf 'config\t%s\n'  "${MUX_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/$PKG}"
  _p_st=${XDG_STATE_HOME:-$HOME/.local/state}
  printf 'state\t%s\n'   "${MUX_STATE:-$_p_st/$PKG}"
  printf 'cache\t%s\n'   "${MUX_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/$PKG}"
  _p_rt=${XDG_RUNTIME_DIR:-/tmp/user-$(id -u)}
  printf 'runtime\t%s\n' "$_p_rt/$PKG"
  printf 'venv\t%s\n'    "${MUX_INDICATOR_VENV:-$_pay/venv}"
  printf 'policy\t%s\n'  "/etc/$PKG/send-policy"
}

_U="usage: setup.sh [install|uninstall|check|paths|test|version|all|indicator]"
case "${1:-help}" in
  install)   do_install ;;
  uninstall) do_uninstall ;;
  check)     do_check; exit "$RC" ;;
  paths)     do_paths ;;
  test)      exec sh "$_root/test/run" ;;
  version)   _v=$(git -C "$_root" describe --tags --always 2>/dev/null || true)
             echo "${_v:-$PKG (unversioned)}" ;;
  all)       do_install; sh "$_root/indicator/setup.sh" install ;;
  indicator) shift; exec sh "$_root/indicator/setup.sh" "$@" ;;  # passthrough
  -h|--help|help) echo "$_U" ;;
  *) echo "setup.sh: unknown command '${1:-}'" >&2; echo "$_U" >&2; exit 2 ;;
esac
